spring:
  profiles:
    group:
      development:
        - common
      production:
        - common
    active: production

---
spring:
  config:
    activate:
      on-profile: development
  datasource:
    url: 'jdbc:h2:mem:real_estate'
    username: 'real_estate'
    password: 'real_estate'
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: '/h2-console'

---
spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:mariadb://localhost:3306/real_estate?characterEncoding=UTF-8&serverTimezone=UTC
    username: 'real_estate'
    password: 'real_estate'
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      max-lifetime: 58000

---
spring:
  config:
    activate:
      on-profile: common
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  messages:
    basename: i18n/messages
    encoding: UTF-8