spring:
  profiles:
    group:
      development:
        - common
      production:
        - common
    active: production

---
spring:
  config:
    activate:
      on-profile: development
  datasource:
    url: 'jdbc:h2:mem:real_estate'
    username: 'real_estate'
    password: 'real_estate'
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: '/h2-console'

---
spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:log4jdbc:mariadb://localhost:3306/real_estate?characterEncoding=UTF-8&serverTimezone=UTC
    username: 'real_estate'
    password: 'real_estate'
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    hikari:
      max-lifetime: 58000

---
spring:
  config:
    activate:
      on-profile: common
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
  messages:
    basename: i18n/messages
    encoding: UTF-8
logging:
  level:
    com:
      zaxxer:
        hikari: INFO
    javax:
      sql:
        DataSource: OFF
    jdbc:
      audit: OFF # JDBC 트러블슈팅 경우를 제외하고는 사용 권장 X
      resultset: OFF # ResultSet을 포함한 모든 JDBC 호출 정보를 출력
      resultsettable: INFO  #SQL 결과 데이터 Table형식으로 출력
      sqlonly: OFF     #SQL만 로그만 출력
      sqltiming: INFO    #SQL + 소요시간 출력
      connection : OFF  # 커넥션 연결/종료 정보 출력